using System.Collections.Generic;
using System.Text;

namespace Ghostty.Core.Settings;

/// <summary>
/// The one-line-per-shader config file that hands libghostty a live path for
/// the <c>gallery:&lt;id&gt;</c> tokens a user's <c>custom-shader</c> names.
/// </summary>
/// <remarks>
/// The user's file keeps the token (that is the whole point of the token: an
/// update, a move, or a different install prefix cannot invalidate it), and
/// every config build layers this over the user's files so the renderer is
/// handed a path that exists in this install. The same shape as the theme
/// preview overlay and the High Contrast override, for the same reason:
/// libghostty knows paths, and the app owns the tokens.
/// </remarks>
public static class ShaderGalleryOverlay
{
    /// <summary>
    /// The config key this resolves. A Zig <c>RepeatablePath</c>, so the
    /// semantics below follow that type rather than a scalar key's.
    /// </summary>
    public const string ConfigKey = "custom-shader";

    /// <summary>
    /// The overlay body for <paramref name="configuredValues"/>, or null when
    /// there is nothing to layer -- no value is one of our tokens, so the
    /// user's config already says what libghostty needs.
    /// </summary>
    /// <remarks>
    /// The body CLEARS the key before restating it, which is how a repeatable
    /// key is replaced rather than appended to: ghostty's parser assigns the
    /// field default for an empty value, and the default for a repeatable is
    /// the empty list. Without the clear line the token the user's own file
    /// names would stay in the list ahead of the resolved path, and the
    /// renderer aborts the whole chain on the first entry it cannot open --
    /// so appending would be the same silent no-shader this fixes, one layer
    /// deeper.
    /// <para>
    /// Every configured value is restated, not only the tokens: a config can
    /// name a gallery shader and a hand-written path together, and dropping
    /// the second would lose a setting the user has always had.
    /// </para>
    /// <para>
    /// A value this install cannot resolve -- a token whose entry is not in the
    /// manifest, or a plain path -- is restated verbatim, and a list of
    /// nothing-but-unresolvable values layers nothing at all: the user's own
    /// line already says what libghostty reads, and the shader notice the app
    /// already has is what explains a file that will not open.
    /// </para>
    /// </remarks>
    public static string? RenderFor(IReadOnlyList<string> configuredValues)
    {
        if (configuredValues is null || configuredValues.Count == 0) return null;

        var lines = new List<string>(configuredValues.Count + 2);
        var sawToken = false;
        foreach (var value in configuredValues)
        {
            var resolved = ShaderGallery.ResolveTokenToPath(value);
            if (resolved is null) lines.Add(value);
            else
            {
                lines.Add(resolved);
                sawToken = true;
            }
        }

        if (!sawToken) return null;

        var body = new StringBuilder();
        body.AppendLine("# Generated by Wintty; do not edit. The gallery:<id> values in");
        body.AppendLine("# your config resolved to this install's shader paths.");
        body.AppendLine($"{ConfigKey} =");
        foreach (var line in lines) body.AppendLine($"{ConfigKey} = {line}");
        return body.ToString();
    }
}
